openapi: 3.0.0
info:
    title: Blob Storage API
    description: API for storing and retrieving blobs of data
    version: 0.1.0
servers:
    - url: http://localhost:8081
      description: Local instance
paths:
  /api/v1/blobs/upload:
    post:
      summary: Upload blob
      operationId: uploadBlob
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
      responses:
        201:
          description: Blob uploaded successfully