// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package api

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// UploadBlobMultipartBody defines parameters for UploadBlob.
type UploadBlobMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UploadBlobMultipartRequestBody defines body for UploadBlob for multipart/form-data ContentType.
type UploadBlobMultipartRequestBody UploadBlobMultipartBody
