// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package api

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// UploadBookMultipartBody defines parameters for UploadBook.
type UploadBookMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UploadBookMultipartRequestBody defines body for UploadBook for multipart/form-data ContentType.
type UploadBookMultipartRequestBody UploadBookMultipartBody
