openapi: 3.0.0
info:
    title: Reader API
    description: API for book managing and reading
    version: 0.1.0
servers:
    - url: http://localhost:8080
      description: Local instance
paths:
  /books/upload:
    post:
      summary: Upload new book for processing
      operationId: uploadBook
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
      responses:
        201:
          description: Book uploaded successfully